Add addgroup function
jsonar/mock pull request #1
Opened 2020-10-05 14:47 UTC by maorJsonar

2020-10-05 18:52 UTC, oorijsonar requested changes

2020-10-05 18:52 UTC, oorijsonar commented on grp.py
> +    def addgroup(self, name, gid=None):
Rename to `groupadd`. Like Linux!

2020-10-05 18:52 UTC, oorijsonar commented on grp.py
> +            gid = self.db[-1].gr_gid + 1
I don't get this. Why is this the value you're assigning to the `gid`?

2020-10-05 18:52 UTC, oorijsonar commented on grp.py
> +    def addgroup(self, name, gid=None):
Should this function be okay with any input and not raise exceptions?

2020-10-05 19:44 UTC, maorJsonar commented on grp.py
> +            gid = self.db[-1].gr_gid + 1
If the user doesn't provide the gid I just thought to take the last gid and increase it by 1.

2020-10-05 19:49 UTC, oorijsonar commented on grp.py
> +            gid = self.db[-1].gr_gid + 1
That might be taken though, no?

2020-10-05 21:03 UTC, maorJsonar commented on grp.py
> +    def addgroup(self, name, gid=None):
Added some validation.

2020-10-06 03:01 UTC, oorijsonar requested changes

2020-10-06 03:01 UTC, oorijsonar commented on grp.py
> +    def groupadd(self, args):
You can't raise random exceptions in the mock. You have to see what kind of exception the mocked function would raise in these cases (my guess is `CalledProcessError`).

2020-10-06 04:56 UTC, maorJsonar commented on grp.py
> +    def groupadd(self, args):
Done

2020-10-06 05:02 UTC, oorijsonar commented on grp.py
> +            gid = max([group.gr_gid for group in self.db])
Will this work? The max is already there isn't it?

2020-10-06 05:09 UTC, maorJsonar commented on grp.py
> +            gid = max([group.gr_gid for group in self.db])
Nop, you are right, sorry its probably the hour.

2020-10-06 05:09 UTC, oorijsonar approved these changes
Does the `CalledProcessError` really have that as a message?

2020-10-06 05:09 UTC, merged

2020-10-06 16:46 UTC, maorJsonar commented
> Does the `CalledProcessError` really have that as a message?

Yes, that's what I got trying to run it with the original `process.run()`