Add mock useradd to pwd
jsonar/mock pull request #2
Opened 2020-10-07 16:25 UTC by maorJsonar

2020-10-07 18:08 UTC, oorijsonar requested changes

2020-10-07 18:08 UTC, oorijsonar commented on pwd.py
> +        self.db.append(struct_passwd(username, 'x', int(uid), 981,
If you got a `groupname` then shouldn't the `gid` correspond to it and not be a hard coded 981? Does the other mock you wrote have the same problem?

2020-10-07 18:08 UTC, oorijsonar commented on pwd.py
> +                raise TypeError(f"expected str, bytes or os.PathLike object, not {type(arg)}")
This code looks familiar...

2020-10-07 23:28 UTC, maorJsonar commented on pwd.py
> +                raise TypeError(f"expected str, bytes or os.PathLike object, not {type(arg)}")
Added base class with this code.

2020-10-07 23:30 UTC, maorJsonar commented on pwd.py
> +        self.db.append(struct_passwd(username, 'x', int(uid), 981,
We have decided to leave this as is for now.

2020-10-07 23:52 UTC, yhagerjs commented
Why do we need this? The original grp/pwd don't have this function. What's the point in mocking something that doesn't exist? The mocked classes already contain a mechanism to initialize a list of users/groups - the idea was to use that and keep the original API, not enhance the stdlib grp/pwd modules.

2020-10-07 23:58 UTC, oorijsonar commented
> Why do we need this? The original grp/pwd don't have this function. What's the point in mocking something that doesn't exist? The mocked classes already contain a mechanism to initialize a list of users/groups - the idea was to use that and keep the original API, not enhance the stdlib grp/pwd modules.

To be able to test that we pass the arguments properly (we didn't pass them properly https://github.com/jsonar/sonarg/issues/1776).

2020-10-07 23:59 UTC, yhagerjs commented
You are referring to the string validation? I'm asking about the `useradd`/`groupadd` functions.

2020-10-08 00:00 UTC, oorijsonar commented
> You are referring to the string validation? I'm asking about the `useradd`/`groupadd` functions.

Please see the pull request that uses this one.

2020-10-08 00:27 UTC, oorijsonar requested changes

2020-10-08 00:27 UTC, oorijsonar commented on ent.py
> +class MockEnt:
1. Rename this file to `subprocess.py`
2. Rename the function to `validate` or `validate_run_args`.
3. Make the function the only thing in this file (no classes).

2020-10-08 01:47 UTC, oorijsonar requested changes

2020-10-08 01:47 UTC, oorijsonar commented on grp.py
> +class MockGrp():
No need for this change.

2020-10-08 01:47 UTC, oorijsonar commented on pwd.py
> +class MockPwd():
No need for this change.

2020-10-08 01:51 UTC, merged